/**
 * Supabase-generated database types.
 *
 * Regenerated by `pnpm --filter @homehub/db db:types`. Do NOT hand-edit.
 * Regenerated for M3-A against migrations 0001-0011 (app.* core tables,
 * sync.*, audit.event, app.model_calls, mem.* graph tables).
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  app: {
    Tables: {
      account: {
        Row: {
          balance_cents: number | null;
          created_at: string;
          currency: string;
          external_id: string | null;
          household_id: string;
          id: string;
          kind: string;
          last_synced_at: string | null;
          name: string;
          owner_member_id: string | null;
          provider: string | null;
          updated_at: string;
        };
        Insert: {
          balance_cents?: number | null;
          created_at?: string;
          currency?: string;
          external_id?: string | null;
          household_id: string;
          id?: string;
          kind: string;
          last_synced_at?: string | null;
          name: string;
          owner_member_id?: string | null;
          provider?: string | null;
          updated_at?: string;
        };
        Update: {
          balance_cents?: number | null;
          created_at?: string;
          currency?: string;
          external_id?: string | null;
          household_id?: string;
          id?: string;
          kind?: string;
          last_synced_at?: string | null;
          name?: string;
          owner_member_id?: string | null;
          provider?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'account_owner_member_id_fkey';
            columns: ['owner_member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      account_grant: {
        Row: {
          access: string;
          account_id: string;
          id: string;
          member_id: string;
        };
        Insert: {
          access: string;
          account_id: string;
          id?: string;
          member_id: string;
        };
        Update: {
          access?: string;
          account_id?: string;
          id?: string;
          member_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_grant_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'account';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'account_grant_member_id_fkey';
            columns: ['member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      action: {
        Row: {
          created_at: string;
          created_by: string | null;
          error: string | null;
          finished_at: string | null;
          household_id: string;
          id: string;
          kind: string;
          payload: Json;
          result: Json | null;
          segment: string;
          started_at: string | null;
          status: string;
          suggestion_id: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          error?: string | null;
          finished_at?: string | null;
          household_id: string;
          id?: string;
          kind: string;
          payload?: Json;
          result?: Json | null;
          segment: string;
          started_at?: string | null;
          status?: string;
          suggestion_id?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          error?: string | null;
          finished_at?: string | null;
          household_id?: string;
          id?: string;
          kind?: string;
          payload?: Json;
          result?: Json | null;
          segment?: string;
          started_at?: string | null;
          status?: string;
          suggestion_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'action_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'action_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'action_suggestion_id_fkey';
            columns: ['suggestion_id'];
            isOneToOne: false;
            referencedRelation: 'suggestion';
            referencedColumns: ['id'];
          },
        ];
      };
      alert: {
        Row: {
          body: string;
          context: Json;
          dismissed_at: string | null;
          dismissed_by: string | null;
          generated_at: string;
          generated_by: string;
          household_id: string;
          id: string;
          segment: string;
          severity: string;
          title: string;
        };
        Insert: {
          body: string;
          context?: Json;
          dismissed_at?: string | null;
          dismissed_by?: string | null;
          generated_at?: string;
          generated_by: string;
          household_id: string;
          id?: string;
          segment: string;
          severity: string;
          title: string;
        };
        Update: {
          body?: string;
          context?: Json;
          dismissed_at?: string | null;
          dismissed_by?: string | null;
          generated_at?: string;
          generated_by?: string;
          household_id?: string;
          id?: string;
          segment?: string;
          severity?: string;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'alert_dismissed_by_fkey';
            columns: ['dismissed_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'alert_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      budget: {
        Row: {
          amount_cents: number;
          category: string;
          created_at: string;
          currency: string;
          household_id: string;
          id: string;
          name: string;
          period: string;
          updated_at: string;
        };
        Insert: {
          amount_cents: number;
          category: string;
          created_at?: string;
          currency?: string;
          household_id: string;
          id?: string;
          name: string;
          period: string;
          updated_at?: string;
        };
        Update: {
          amount_cents?: number;
          category?: string;
          created_at?: string;
          currency?: string;
          household_id?: string;
          id?: string;
          name?: string;
          period?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'budget_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      conversation: {
        Row: {
          archived_at: string | null;
          created_at: string;
          created_by: string | null;
          household_id: string;
          id: string;
          last_message_at: string;
          pinned: boolean;
          title: string | null;
        };
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          household_id: string;
          id?: string;
          last_message_at?: string;
          pinned?: boolean;
          title?: string | null;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          household_id?: string;
          id?: string;
          last_message_at?: string;
          pinned?: boolean;
          title?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'conversation_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'conversation_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      conversation_attachment: {
        Row: {
          conversation_id: string;
          created_at: string;
          household_id: string;
          id: string;
          mime_type: string;
          processed_as: string | null;
          storage_path: string;
          turn_id: string | null;
        };
        Insert: {
          conversation_id: string;
          created_at?: string;
          household_id: string;
          id?: string;
          mime_type: string;
          processed_as?: string | null;
          storage_path: string;
          turn_id?: string | null;
        };
        Update: {
          conversation_id?: string;
          created_at?: string;
          household_id?: string;
          id?: string;
          mime_type?: string;
          processed_as?: string | null;
          storage_path?: string;
          turn_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'conversation_attachment_conversation_id_fkey';
            columns: ['conversation_id'];
            isOneToOne: false;
            referencedRelation: 'conversation';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'conversation_attachment_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'conversation_attachment_turn_id_fkey';
            columns: ['turn_id'];
            isOneToOne: false;
            referencedRelation: 'conversation_turn';
            referencedColumns: ['id'];
          },
        ];
      };
      conversation_turn: {
        Row: {
          author_member_id: string | null;
          body_md: string;
          citations: Json | null;
          conversation_id: string;
          cost_cents: number | null;
          created_at: string;
          household_id: string;
          id: string;
          input_tokens: number | null;
          model: string | null;
          no_memory_write: boolean;
          output_tokens: number | null;
          role: string;
          tool_calls: Json | null;
        };
        Insert: {
          author_member_id?: string | null;
          body_md?: string;
          citations?: Json | null;
          conversation_id: string;
          cost_cents?: number | null;
          created_at?: string;
          household_id: string;
          id?: string;
          input_tokens?: number | null;
          model?: string | null;
          no_memory_write?: boolean;
          output_tokens?: number | null;
          role: string;
          tool_calls?: Json | null;
        };
        Update: {
          author_member_id?: string | null;
          body_md?: string;
          citations?: Json | null;
          conversation_id?: string;
          cost_cents?: number | null;
          created_at?: string;
          household_id?: string;
          id?: string;
          input_tokens?: number | null;
          model?: string | null;
          no_memory_write?: boolean;
          output_tokens?: number | null;
          role?: string;
          tool_calls?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: 'conversation_turn_author_member_id_fkey';
            columns: ['author_member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'conversation_turn_conversation_id_fkey';
            columns: ['conversation_id'];
            isOneToOne: false;
            referencedRelation: 'conversation';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'conversation_turn_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      event: {
        Row: {
          all_day: boolean;
          created_at: string;
          ends_at: string | null;
          household_id: string;
          id: string;
          kind: string;
          location: string | null;
          metadata: Json;
          owner_member_id: string | null;
          provider: string | null;
          segment: string;
          source_id: string | null;
          source_version: string | null;
          starts_at: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          all_day?: boolean;
          created_at?: string;
          ends_at?: string | null;
          household_id: string;
          id?: string;
          kind: string;
          location?: string | null;
          metadata?: Json;
          owner_member_id?: string | null;
          provider?: string | null;
          segment: string;
          source_id?: string | null;
          source_version?: string | null;
          starts_at: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          all_day?: boolean;
          created_at?: string;
          ends_at?: string | null;
          household_id?: string;
          id?: string;
          kind?: string;
          location?: string | null;
          metadata?: Json;
          owner_member_id?: string | null;
          provider?: string | null;
          segment?: string;
          source_id?: string | null;
          source_version?: string | null;
          starts_at?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'event_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'event_owner_member_id_fkey';
            columns: ['owner_member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      grocery_list: {
        Row: {
          created_at: string;
          external_order_id: string | null;
          household_id: string;
          id: string;
          planned_for: string | null;
          provider: string | null;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          external_order_id?: string | null;
          household_id: string;
          id?: string;
          planned_for?: string | null;
          provider?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          external_order_id?: string | null;
          household_id?: string;
          id?: string;
          planned_for?: string | null;
          provider?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'grocery_list_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      grocery_list_item: {
        Row: {
          checked: boolean;
          created_at: string;
          household_id: string;
          id: string;
          list_id: string;
          name: string;
          quantity: number | null;
          source_meal_id: string | null;
          unit: string | null;
        };
        Insert: {
          checked?: boolean;
          created_at?: string;
          household_id: string;
          id?: string;
          list_id: string;
          name: string;
          quantity?: number | null;
          source_meal_id?: string | null;
          unit?: string | null;
        };
        Update: {
          checked?: boolean;
          created_at?: string;
          household_id?: string;
          id?: string;
          list_id?: string;
          name?: string;
          quantity?: number | null;
          source_meal_id?: string | null;
          unit?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'grocery_list_item_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'grocery_list_item_list_id_fkey';
            columns: ['list_id'];
            isOneToOne: false;
            referencedRelation: 'grocery_list';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'grocery_list_item_source_meal_id_fkey';
            columns: ['source_meal_id'];
            isOneToOne: false;
            referencedRelation: 'meal';
            referencedColumns: ['id'];
          },
        ];
      };
      household: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          name: string;
          settings: Json;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name: string;
          settings?: Json;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name?: string;
          settings?: Json;
        };
        Relationships: [];
      };
      household_invitation: {
        Row: {
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
          email: string;
          expires_at: string;
          household_id: string;
          id: string;
          invited_by: string;
          proposed_grants: Json;
          role: string;
          token_hash: string;
        };
        Insert: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email: string;
          expires_at: string;
          household_id: string;
          id?: string;
          invited_by: string;
          proposed_grants?: Json;
          role: string;
          token_hash: string;
        };
        Update: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email?: string;
          expires_at?: string;
          household_id?: string;
          id?: string;
          invited_by?: string;
          proposed_grants?: Json;
          role?: string;
          token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'household_invitation_accepted_by_fkey';
            columns: ['accepted_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'household_invitation_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'household_invitation_invited_by_fkey';
            columns: ['invited_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      meal: {
        Row: {
          cook_member_id: string | null;
          created_at: string;
          dish_node_id: string | null;
          household_id: string;
          id: string;
          notes: string | null;
          planned_for: string;
          servings: number | null;
          slot: string;
          status: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          cook_member_id?: string | null;
          created_at?: string;
          dish_node_id?: string | null;
          household_id: string;
          id?: string;
          notes?: string | null;
          planned_for: string;
          servings?: number | null;
          slot: string;
          status?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          cook_member_id?: string | null;
          created_at?: string;
          dish_node_id?: string | null;
          household_id?: string;
          id?: string;
          notes?: string | null;
          planned_for?: string;
          servings?: number | null;
          slot?: string;
          status?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'meal_cook_member_id_fkey';
            columns: ['cook_member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'meal_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      member: {
        Row: {
          display_name: string;
          email: string | null;
          household_id: string;
          id: string;
          invited_at: string;
          joined_at: string | null;
          role: string;
          user_id: string | null;
        };
        Insert: {
          display_name: string;
          email?: string | null;
          household_id: string;
          id?: string;
          invited_at?: string;
          joined_at?: string | null;
          role: string;
          user_id?: string | null;
        };
        Update: {
          display_name?: string;
          email?: string | null;
          household_id?: string;
          id?: string;
          invited_at?: string;
          joined_at?: string | null;
          role?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'member_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      member_segment_grant: {
        Row: {
          access: string;
          id: string;
          member_id: string;
          segment: string;
        };
        Insert: {
          access: string;
          id?: string;
          member_id: string;
          segment: string;
        };
        Update: {
          access?: string;
          id?: string;
          member_id?: string;
          segment?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'member_segment_grant_member_id_fkey';
            columns: ['member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      model_calls: {
        Row: {
          at: string;
          cost_usd: number;
          household_id: string;
          id: string;
          input_tokens: number;
          latency_ms: number | null;
          model: string;
          output_tokens: number;
          task: string;
        };
        Insert: {
          at?: string;
          cost_usd?: number;
          household_id: string;
          id?: string;
          input_tokens?: number;
          latency_ms?: number | null;
          model: string;
          output_tokens?: number;
          task: string;
        };
        Update: {
          at?: string;
          cost_usd?: number;
          household_id?: string;
          id?: string;
          input_tokens?: number;
          latency_ms?: number | null;
          model?: string;
          output_tokens?: number;
          task?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'model_calls_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      pantry_item: {
        Row: {
          created_at: string;
          expires_on: string | null;
          household_id: string;
          id: string;
          last_seen_at: string | null;
          location: string | null;
          name: string;
          quantity: number | null;
          unit: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          expires_on?: string | null;
          household_id: string;
          id?: string;
          last_seen_at?: string | null;
          location?: string | null;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          expires_on?: string | null;
          household_id?: string;
          id?: string;
          last_seen_at?: string | null;
          location?: string | null;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'pantry_item_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      person: {
        Row: {
          aliases: string[];
          display_name: string;
          household_id: string;
          id: string;
          member_id: string | null;
          metadata: Json;
          relationship: string | null;
        };
        Insert: {
          aliases?: string[];
          display_name: string;
          household_id: string;
          id?: string;
          member_id?: string | null;
          metadata?: Json;
          relationship?: string | null;
        };
        Update: {
          aliases?: string[];
          display_name?: string;
          household_id?: string;
          id?: string;
          member_id?: string | null;
          metadata?: Json;
          relationship?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'person_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'person_member_id_fkey';
            columns: ['member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      suggestion: {
        Row: {
          created_at: string;
          household_id: string;
          id: string;
          kind: string;
          preview: Json;
          rationale: string;
          resolved_at: string | null;
          resolved_by: string | null;
          segment: string;
          status: string;
          title: string;
        };
        Insert: {
          created_at?: string;
          household_id: string;
          id?: string;
          kind: string;
          preview?: Json;
          rationale: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          segment: string;
          status?: string;
          title: string;
        };
        Update: {
          created_at?: string;
          household_id?: string;
          id?: string;
          kind?: string;
          preview?: Json;
          rationale?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          segment?: string;
          status?: string;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'suggestion_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'suggestion_resolved_by_fkey';
            columns: ['resolved_by'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
      summary: {
        Row: {
          body_md: string;
          covered_end: string;
          covered_start: string;
          generated_at: string;
          household_id: string;
          id: string;
          model: string;
          period: string;
          segment: string;
        };
        Insert: {
          body_md: string;
          covered_end: string;
          covered_start: string;
          generated_at?: string;
          household_id: string;
          id?: string;
          model: string;
          period: string;
          segment: string;
        };
        Update: {
          body_md?: string;
          covered_end?: string;
          covered_start?: string;
          generated_at?: string;
          household_id?: string;
          id?: string;
          model?: string;
          period?: string;
          segment?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'summary_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
        ];
      };
      transaction: {
        Row: {
          account_id: string | null;
          amount_cents: number;
          category: string | null;
          created_at: string;
          currency: string;
          household_id: string;
          id: string;
          member_id: string | null;
          merchant_raw: string | null;
          metadata: Json;
          occurred_at: string;
          source: string;
          source_id: string | null;
          source_version: string | null;
          updated_at: string;
        };
        Insert: {
          account_id?: string | null;
          amount_cents: number;
          category?: string | null;
          created_at?: string;
          currency?: string;
          household_id: string;
          id?: string;
          member_id?: string | null;
          merchant_raw?: string | null;
          metadata?: Json;
          occurred_at: string;
          source: string;
          source_id?: string | null;
          source_version?: string | null;
          updated_at?: string;
        };
        Update: {
          account_id?: string | null;
          amount_cents?: number;
          category?: string | null;
          created_at?: string;
          currency?: string;
          household_id?: string;
          id?: string;
          member_id?: string | null;
          merchant_raw?: string | null;
          metadata?: Json;
          occurred_at?: string;
          source?: string;
          source_id?: string | null;
          source_version?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'transaction_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'account';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'transaction_household_id_fkey';
            columns: ['household_id'];
            isOneToOne: false;
            referencedRelation: 'household';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'transaction_member_id_fkey';
            columns: ['member_id'];
            isOneToOne: false;
            referencedRelation: 'member';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      can_read_account: { Args: { account_id: string }; Returns: boolean };
      can_read_segment: {
        Args: { h: string; segment: string };
        Returns: boolean;
      };
      can_write_account: { Args: { account_id: string }; Returns: boolean };
      can_write_segment: {
        Args: { h: string; segment: string };
        Returns: boolean;
      };
      current_user_id: { Args: never; Returns: string };
      is_member: { Args: { h: string }; Returns: boolean };
      member_id: { Args: { h: string }; Returns: string };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  audit: {
    Tables: {
      event: {
        Row: {
          action: string;
          actor_user_id: string | null;
          after: Json | null;
          at: string;
          before: Json | null;
          household_id: string | null;
          id: string;
          resource_id: string | null;
          resource_type: string;
        };
        Insert: {
          action: string;
          actor_user_id?: string | null;
          after?: Json | null;
          at?: string;
          before?: Json | null;
          household_id?: string | null;
          id?: string;
          resource_id?: string | null;
          resource_type: string;
        };
        Update: {
          action?: string;
          actor_user_id?: string | null;
          after?: Json | null;
          at?: string;
          before?: Json | null;
          household_id?: string | null;
          id?: string;
          resource_id?: string | null;
          resource_type?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  mem: {
    Tables: {
      alias: {
        Row: {
          alias: string;
          created_at: string;
          household_id: string;
          id: string;
          node_id: string;
          source: string;
        };
        Insert: {
          alias: string;
          created_at?: string;
          household_id: string;
          id?: string;
          node_id: string;
          source: string;
        };
        Update: {
          alias?: string;
          created_at?: string;
          household_id?: string;
          id?: string;
          node_id?: string;
          source?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'alias_node_id_fkey';
            columns: ['node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
        ];
      };
      edge: {
        Row: {
          created_at: string;
          dst_id: string;
          evidence: Json;
          household_id: string;
          id: string;
          src_id: string;
          type: string;
          updated_at: string;
          weight: number;
        };
        Insert: {
          created_at?: string;
          dst_id: string;
          evidence?: Json;
          household_id: string;
          id?: string;
          src_id: string;
          type: string;
          updated_at?: string;
          weight?: number;
        };
        Update: {
          created_at?: string;
          dst_id?: string;
          evidence?: Json;
          household_id?: string;
          id?: string;
          src_id?: string;
          type?: string;
          updated_at?: string;
          weight?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'edge_dst_id_fkey';
            columns: ['dst_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'edge_src_id_fkey';
            columns: ['src_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
        ];
      };
      episode: {
        Row: {
          embedding: string | null;
          ended_at: string | null;
          household_id: string;
          id: string;
          metadata: Json;
          occurred_at: string;
          participants: string[];
          place_node_id: string | null;
          recorded_at: string;
          source_id: string;
          source_type: string;
          summary: string | null;
          title: string;
        };
        Insert: {
          embedding?: string | null;
          ended_at?: string | null;
          household_id: string;
          id?: string;
          metadata?: Json;
          occurred_at: string;
          participants?: string[];
          place_node_id?: string | null;
          recorded_at?: string;
          source_id: string;
          source_type: string;
          summary?: string | null;
          title: string;
        };
        Update: {
          embedding?: string | null;
          ended_at?: string | null;
          household_id?: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          participants?: string[];
          place_node_id?: string | null;
          recorded_at?: string;
          source_id?: string;
          source_type?: string;
          summary?: string | null;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'episode_place_node_id_fkey';
            columns: ['place_node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
        ];
      };
      fact: {
        Row: {
          confidence: number;
          conflict_status: string;
          evidence: Json;
          household_id: string;
          id: string;
          last_reinforced_at: string;
          object_node_id: string | null;
          object_value: Json | null;
          predicate: string;
          recorded_at: string;
          reinforcement_count: number;
          source: string;
          subject_node_id: string;
          superseded_at: string | null;
          superseded_by: string | null;
          valid_from: string;
          valid_to: string | null;
        };
        Insert: {
          confidence: number;
          conflict_status?: string;
          evidence?: Json;
          household_id: string;
          id?: string;
          last_reinforced_at?: string;
          object_node_id?: string | null;
          object_value?: Json | null;
          predicate: string;
          recorded_at?: string;
          reinforcement_count?: number;
          source: string;
          subject_node_id: string;
          superseded_at?: string | null;
          superseded_by?: string | null;
          valid_from: string;
          valid_to?: string | null;
        };
        Update: {
          confidence?: number;
          conflict_status?: string;
          evidence?: Json;
          household_id?: string;
          id?: string;
          last_reinforced_at?: string;
          object_node_id?: string | null;
          object_value?: Json | null;
          predicate?: string;
          recorded_at?: string;
          reinforcement_count?: number;
          source?: string;
          subject_node_id?: string;
          superseded_at?: string | null;
          superseded_by?: string | null;
          valid_from?: string;
          valid_to?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'fact_object_node_id_fkey';
            columns: ['object_node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'fact_subject_node_id_fkey';
            columns: ['subject_node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'fact_superseded_by_fkey';
            columns: ['superseded_by'];
            isOneToOne: false;
            referencedRelation: 'fact';
            referencedColumns: ['id'];
          },
        ];
      };
      fact_candidate: {
        Row: {
          confidence: number | null;
          evidence: Json;
          household_id: string;
          id: string;
          object_node_id: string | null;
          object_value: Json | null;
          predicate: string;
          promoted_fact_id: string | null;
          reason: string | null;
          recorded_at: string;
          source: string;
          status: string;
          subject_node_id: string | null;
          valid_from: string | null;
          valid_to: string | null;
        };
        Insert: {
          confidence?: number | null;
          evidence?: Json;
          household_id: string;
          id?: string;
          object_node_id?: string | null;
          object_value?: Json | null;
          predicate: string;
          promoted_fact_id?: string | null;
          reason?: string | null;
          recorded_at?: string;
          source: string;
          status?: string;
          subject_node_id?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
        };
        Update: {
          confidence?: number | null;
          evidence?: Json;
          household_id?: string;
          id?: string;
          object_node_id?: string | null;
          object_value?: Json | null;
          predicate?: string;
          promoted_fact_id?: string | null;
          reason?: string | null;
          recorded_at?: string;
          source?: string;
          status?: string;
          subject_node_id?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'fact_candidate_object_node_id_fkey';
            columns: ['object_node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'fact_candidate_promoted_fact_id_fkey';
            columns: ['promoted_fact_id'];
            isOneToOne: false;
            referencedRelation: 'fact';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'fact_candidate_subject_node_id_fkey';
            columns: ['subject_node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
        ];
      };
      insight: {
        Row: {
          body_md: string;
          created_at: string;
          household_id: string;
          id: string;
          promoted_to_rule_id: string | null;
          week_start: string;
        };
        Insert: {
          body_md: string;
          created_at?: string;
          household_id: string;
          id?: string;
          promoted_to_rule_id?: string | null;
          week_start: string;
        };
        Update: {
          body_md?: string;
          created_at?: string;
          household_id?: string;
          id?: string;
          promoted_to_rule_id?: string | null;
          week_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'insight_promoted_to_rule_id_fkey';
            columns: ['promoted_to_rule_id'];
            isOneToOne: false;
            referencedRelation: 'rule';
            referencedColumns: ['id'];
          },
        ];
      };
      mention: {
        Row: {
          first_seen_at: string;
          household_id: string;
          id: string;
          node_id: string;
          row_id: string;
          row_table: string;
        };
        Insert: {
          first_seen_at?: string;
          household_id: string;
          id?: string;
          node_id: string;
          row_id: string;
          row_table: string;
        };
        Update: {
          first_seen_at?: string;
          household_id?: string;
          id?: string;
          node_id?: string;
          row_id?: string;
          row_table?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'mention_node_id_fkey';
            columns: ['node_id'];
            isOneToOne: false;
            referencedRelation: 'node';
            referencedColumns: ['id'];
          },
        ];
      };
      node: {
        Row: {
          canonical_name: string;
          created_at: string;
          document_md: string | null;
          embedding: string | null;
          household_id: string;
          id: string;
          manual_notes_md: string | null;
          metadata: Json;
          needs_review: boolean;
          type: string;
          updated_at: string;
        };
        Insert: {
          canonical_name: string;
          created_at?: string;
          document_md?: string | null;
          embedding?: string | null;
          household_id: string;
          id?: string;
          manual_notes_md?: string | null;
          metadata?: Json;
          needs_review?: boolean;
          type: string;
          updated_at?: string;
        };
        Update: {
          canonical_name?: string;
          created_at?: string;
          document_md?: string | null;
          embedding?: string | null;
          household_id?: string;
          id?: string;
          manual_notes_md?: string | null;
          metadata?: Json;
          needs_review?: boolean;
          type?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pattern: {
        Row: {
          confidence: number;
          description: string;
          household_id: string;
          id: string;
          kind: string;
          last_reinforced_at: string;
          observed_from: string;
          observed_to: string;
          parameters: Json;
          sample_size: number;
          status: string;
        };
        Insert: {
          confidence: number;
          description: string;
          household_id: string;
          id?: string;
          kind: string;
          last_reinforced_at?: string;
          observed_from: string;
          observed_to: string;
          parameters?: Json;
          sample_size: number;
          status?: string;
        };
        Update: {
          confidence?: number;
          description?: string;
          household_id?: string;
          id?: string;
          kind?: string;
          last_reinforced_at?: string;
          observed_from?: string;
          observed_to?: string;
          parameters?: Json;
          sample_size?: number;
          status?: string;
        };
        Relationships: [];
      };
      rule: {
        Row: {
          active: boolean;
          author_member_id: string;
          created_at: string;
          description: string;
          household_id: string;
          id: string;
          predicate_dsl: Json;
        };
        Insert: {
          active?: boolean;
          author_member_id: string;
          created_at?: string;
          description: string;
          household_id: string;
          id?: string;
          predicate_dsl: Json;
        };
        Update: {
          active?: boolean;
          author_member_id?: string;
          created_at?: string;
          description?: string;
          household_id?: string;
          id?: string;
          predicate_dsl?: Json;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  sync: {
    Tables: {
      cursor: {
        Row: {
          connection_id: string;
          id: string;
          kind: string;
          updated_at: string;
          value: string | null;
        };
        Insert: {
          connection_id: string;
          id?: string;
          kind: string;
          updated_at?: string;
          value?: string | null;
        };
        Update: {
          connection_id?: string;
          id?: string;
          kind?: string;
          updated_at?: string;
          value?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'cursor_connection_id_fkey';
            columns: ['connection_id'];
            isOneToOne: false;
            referencedRelation: 'provider_connection';
            referencedColumns: ['id'];
          },
        ];
      };
      dead_letter: {
        Row: {
          connection_id: string | null;
          error: string;
          id: string;
          message_id: number | null;
          payload: Json;
          queue: string;
          received_at: string;
        };
        Insert: {
          connection_id?: string | null;
          error: string;
          id?: string;
          message_id?: number | null;
          payload: Json;
          queue: string;
          received_at?: string;
        };
        Update: {
          connection_id?: string | null;
          error?: string;
          id?: string;
          message_id?: number | null;
          payload?: Json;
          queue?: string;
          received_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'dead_letter_connection_id_fkey';
            columns: ['connection_id'];
            isOneToOne: false;
            referencedRelation: 'provider_connection';
            referencedColumns: ['id'];
          },
        ];
      };
      provider_connection: {
        Row: {
          created_at: string;
          household_id: string;
          id: string;
          last_synced_at: string | null;
          member_id: string | null;
          nango_connection_id: string;
          provider: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          household_id: string;
          id?: string;
          last_synced_at?: string | null;
          member_id?: string | null;
          nango_connection_id: string;
          provider: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          household_id?: string;
          id?: string;
          last_synced_at?: string | null;
          member_id?: string | null;
          nango_connection_id?: string;
          provider?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  app: {
    Enums: {},
  },
  audit: {
    Enums: {},
  },
  mem: {
    Enums: {},
  },
  sync: {
    Enums: {},
  },
} as const;
