/**
 * Supabase-generated database types.
 *
 * This file is regenerated by `pnpm db:types` against the local Supabase
 * stack. It is a placeholder until M1 introduces the first application
 * tables — at that point running `pnpm db:types` will overwrite this file
 * with the real schema types.
 *
 * Do NOT hand-edit. The file is checked in so downstream packages can
 * typecheck without a running Supabase stack.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

/**
 * Placeholder `Database` shape. Mirrors the structure that
 * `supabase gen types typescript` emits so consumers can start wiring
 * imports today and get real types on the next regeneration.
 */
export interface Database {
  app: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
  mem: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
  sync: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
  audit: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
